In [1]:
import os,warnings,time,numpy as np,pandas as pd,matplotlib.pyplot as plt,seaborn as sns
from sklearn.model_selection import StratifiedKFold, train_test_split
from sklearn.preprocessing import LabelEncoder , StandardScaler
from sklearn.metrics import accuracy_score,f1_score,classification_report,confusion_matrix,cohen_kappa_score,precision_score,recall_score
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier
from xgboost import XGBClassifier
warnings.filterwarnings('ignore');plt.style.use('seaborn-v0_8-whitegrid')
print("READY")

READY

In [5]:
data= pd.read_csv('fetal_health.csv')

In [6]:
data.shape

(2126, 22)

In [7]:
data

,baseline value,accelerations,fetal_movement,uterine_contractions,light_decelerations,severe_decelerations,prolongued_decelerations,abnormal_short_term_variability,mean_value_of_short_term_variability,percentage_of_time_with_abnormal_long_term_variability,...,histogram_min,histogram_max,histogram_number_of_peaks,histogram_number_of_zeroes,histogram_mode,histogram_mean,histogram_median,histogram_variance,histogram_tendency,fetal_health
0,120.0,0.000,0.000,0.000,0.000,0.0,0.0,73.0,0.5,43.0,...,62.0,126.0,2.0,0.0,120.0,137.0,121.0,73.0,1.0,2.0
1,132.0,0.006,0.000,0.006,0.003,0.0,0.0,17.0,2.1,0.0,...,68.0,198.0,6.0,1.0,141.0,136.0,140.0,12.0,0.0,1.0
2,133.0,0.003,0.000,0.008,0.003,0.0,0.0,16.0,2.1,0.0,...,68.0,198.0,5.0,1.0,141.0,135.0,138.0,13.0,0.0,1.0
3,134.0,0.003,0.000,0.008,0.003,0.0,0.0,16.0,2.4,0.0,...,53.0,170.0,11.0,0.0,137.0,134.0,137.0,13.0,1.0,1.0
4,132.0,0.007,0.000,0.008,0.000,0.0,0.0,16.0,2.4,0.0,...,53.0,170.0,9.0,0.0,137.0,136.0,138.0,11.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2121,140.0,0.000,0.000,0.007,0.000,0.0,0.0,79.0,0.2,25.0,...,137.0,177.0,4.0,0.0,153.0,150.0,152.0,2.0,0.0,2.0
2122,140.0,0.001,0.000,0.007,0.000,0.0,0.0,78.0,0.4,22.0,...,103.0,169.0,6.0,0.0,152.0,148.0,151.0,3.0,1.0,2.0
2123,140.0,0.001,0.000,0.007,0.000,0.0,0.0,79.0,0.4,20.0,...,103.0,170.0,5.0,0.0,153.0,148.0,152.0,4.0,1.0,2.0
2124,140.0,0.001,0.000,0.006,0.000,0.0,0.0,78.0,0.4,27.0,...,103.0,169.0,6.0,0.0,152.0,147.0,151.0,4.0,1.0,2.0
2125,142.0,0.002,0.002,0.008,0.000,0.0,0.0,74.0,0.4,36.0,...,117.0,159.0,2.0,1.0,145.0,143.0,145.0,1.0,0.0,1.0

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2126 entries, 0 to 2125
Data columns (total 22 columns):
 #   Column                                                  Non-Null Count  Dtype
---  ------                                                  --------------  -----
 0   baseline value                                          2126 non-null   float64
 1   accelerations                                           2126 non-null   float64
 2   fetal_movement                                          2126 non-null   float64
 3   uterine_contractions                                    2126 non-null   float64
 4   light_decelerations                                     2126 non-null   float64
 5   severe_decelerations                                    2126 non-null   float64
 6   prolongued_decelerations                                2126 non-null   float64
 7   abnormal_short_term_variability                         2126 non-null   float64
 8   mean_value_of_short_term_variability                    2126 non-null   float64
 9   percentage_of_time_with_abnormal_long_term_variability  2126 non-null   float64
 10  mean_value_of_long_term_variability                     2126 non-null   float64
 11  histogram_width                                         2126 non-null   float64
 12  histogram_min                                           2126 non-null   float64
 13  histogram_max                                           2126 non-null   float64
 14  histogram_number_of_peaks                               2126 non-null   float64
 15  histogram_number_of_zeroes                              2126 non-null   float64
 16  histogram_mode                                          2126 non-null   float64
 17  histogram_mean                                          2126 non-null   float64
 18  histogram_median                                        2126 non-null   float64
 19  histogram_variance                                      2126 non-null   float64
 20  histogram_tendency                                      2126 non-null   float64
 21  fetal_health                                            2126 non-null   float64
dtypes: float64(22)
memory usage: 365.5 KB

In [9]:
for col in data.columns:
    print(col)

baseline value
accelerations
fetal_movement
uterine_contractions
light_decelerations
severe_decelerations
prolongued_decelerations
abnormal_short_term_variability
mean_value_of_short_term_variability
percentage_of_time_with_abnormal_long_term_variability
mean_value_of_long_term_variability
histogram_width
histogram_min
histogram_max
histogram_number_of_peaks
histogram_number_of_zeroes
histogram_mode
histogram_mean
histogram_median
histogram_variance
histogram_tendency
fetal_health

In [10]:
columns =['baseline value','accelerations','fetal_movement','uterine_contractions','light_decelerations',
          'severe_decelerations','prolongued_decelerations','abnormal_short_term_variability',
          'mean_value_of_short_term_variability',
        'percentage_of_time_with_abnormal_long_term_variability','mean_value_of_long_term_variability',
          'histogram_width','histogram_min',
         'histogram_max','histogram_number_of_peaks','histogram_number_of_zeroes','histogram_mode','histogram_mean',
          'histogram_median','histogram_variance','histogram_tendency']

In [11]:
x = data.drop(['fetal_health'], axis=1)
y = data['fetal_health']

In [12]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42,stratify = y)

In [13]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
X_scaled = scaler.fit_transform(x)

In [14]:
data['fetal_health'].value_counts()

fetal_health
1.0    1655
2.0     295
3.0     176
Name: count, dtype: int64

In [15]:
X_train.shape, X_test.shape

((1700, 21), (426, 21))

In [16]:
y_train.shape, y_test.shape

((1700,), (426,))

# Random Forest

In [17]:
rf = RandomForestClassifier( n_estimators=500,max_depth=10,min_samples_split=5,min_samples_leaf=2,random_state=42)

In [18]:
rf.fit(X_train, y_train)

RandomForestClassifier(max_depth=10, min_samples_leaf=2, min_samples_split=5,
                       n_estimators=500, random_state=42)

In [19]:
y_pred_rf = rf.predict(X_test)

In [20]:
print("Accuracy:", accuracy_score(y_test, y_pred_rf))
print("Precision (macro):", precision_score(y_test, y_pred_rf, average='macro'))
print("Recall (macro):", recall_score(y_test, y_pred_rf, average='macro'))
print("F1 Score (macro):", f1_score(y_test, y_pred_rf, average='macro'))

print("\nClassification Report")
print(classification_report(y_test, y_pred_rf))

print("\nConfusion Matrix")
print(confusion_matrix(y_test, y_pred_rf))

Accuracy: 0.9272300469483568
Precision (macro): 0.903230007814535
Recall (macro): 0.828716804263057
F1 Score (macro): 0.8601898139179541

Classification Report
              precision    recall  f1-score   support

         1.0       0.94      0.98      0.96       332
         2.0       0.86      0.64      0.74        59
         3.0       0.91      0.86      0.88        35

    accuracy                           0.93       426
   macro avg       0.90      0.83      0.86       426
weighted avg       0.92      0.93      0.92       426


Confusion Matrix
[[327   4   1]
 [ 19  38   2]
 [  3   2  30]]

# XGBoost

In [21]:
xgb = XGBClassifier(n_estimators=300,max_depth=6,learning_rate=0.05,subsample=0.8,colsample_bytree=0.8,
                    objective='multi:softmax',num_class=3,random_state=42)

In [22]:
# Shift labels from [1, 2, 3] → [0, 1, 2]
y_train_fixed = y_train - 1
y_test_fixed = y_test - 1

In [23]:
# Train
xgb.fit(X_train, y_train_fixed)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.05, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=300,
              n_jobs=None, num_class=3, ...)

In [24]:
# Predict
y_pred_xgb = xgb.predict(X_test)

In [25]:
# Map predictions back to original labels [1, 2, 3]
y_pred_xgb_original = y_pred_xgb + 1

In [26]:
print("Accuracy:", accuracy_score(y_test, y_pred_xgb_original))
print("Precision (macro):", precision_score(y_test, y_pred_xgb_original, average='macro'))
print("Recall (macro):", recall_score(y_test, y_pred_xgb_original, average='macro'))
print("F1 Score (macro):", f1_score(y_test, y_pred_xgb_original, average='macro'))

print("\nClassification Report")
print(classification_report(y_test, y_pred_xgb_original))

print("\nConfusion Matrix")
print(confusion_matrix(y_test, y_pred_xgb_original))

Accuracy: 0.9389671361502347
Precision (macro): 0.9091216310571149
Recall (macro): 0.8740049787527835
F1 Score (macro): 0.8897004018832884

Classification Report
              precision    recall  f1-score   support

         1.0       0.95      0.98      0.97       332
         2.0       0.86      0.73      0.79        59
         3.0       0.91      0.91      0.91        35

    accuracy                           0.94       426
   macro avg       0.91      0.87      0.89       426
weighted avg       0.94      0.94      0.94       426


Confusion Matrix
[[325   6   1]
 [ 14  43   2]
 [  2   1  32]]

# GradientBoostingClassifier

In [27]:
Gbc =GradientBoostingClassifier(n_estimators=100,random_state=42)

In [28]:
Gbc.fit(X_train,y_train)

GradientBoostingClassifier(random_state=42)

In [29]:
y_pred_gbc =Gbc.predict(X_test)

In [30]:
print("Accuracy:", accuracy_score(y_test, y_pred_gbc))
print("Precision (macro):", precision_score(y_test, y_pred_gbc, average='macro'))
print("Recall (macro):", recall_score(y_test, y_pred_gbc, average='macro'))
print("F1 Score (macro):", f1_score(y_test, y_pred_gbc, average='macro'))

print("\nClassification Report")
print(classification_report(y_test, y_pred_gbc))

print("\nConfusion Matrix")
print(confusion_matrix(y_test, y_pred_gbc))

Accuracy: 0.9272300469483568
Precision (macro): 0.880127723063821
Recall (macro): 0.8550477940818966
F1 Score (macro): 0.8637701463903719

Classification Report
              precision    recall  f1-score   support

         1.0       0.95      0.97      0.96       332
         2.0       0.85      0.68      0.75        59
         3.0       0.84      0.91      0.88        35

    accuracy                           0.93       426
   macro avg       0.88      0.86      0.86       426
weighted avg       0.93      0.93      0.92       426


Confusion Matrix
[[323   6   3]
 [ 16  40   3]
 [  2   1  32]]

In [31]:
final_data=pd.DataFrame({'Models':['Random Forest','XGBoost','GradientBoosting'],"ACC":
                                              [accuracy_score(y_test, y_pred_rf)*100,
                                              accuracy_score(y_test, y_pred_xgb_original)*100,
                                              accuracy_score(y_test, y_pred_gbc)*100,
                                              ]})

In [32]:
final_data

             Models        ACC
0     Random Forest  92.723005
1           XGBoost  93.896714
2  GradientBoosting  92.723005

In [33]:
print(sorted(y.unique()))

[1.0, 2.0, 3.0]

In [34]:
y = y.astype(int) - 1

print(sorted(y.unique()))

[0, 1, 2]

In [35]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(xgb,x,y,cv=5,scoring='accuracy',error_score='raise')

print(scores)
print("Mean:", scores.mean())
print("Std:", scores.std())

[0.90610329 0.92       0.93882353 0.89882353 0.69882353]
Mean: 0.8725147749240542
Std: 0.08790982306282985

In [36]:
import pickle

pickle.dump(xgb,open("final fetal health.pkl",'wb'))
print("Model Saved Successfully")

Model Saved Successfully

In [37]:
le = LabelEncoder()

y_encoded = le.fit_transform(y)

with open("label_encoder_fetal_health.pkl", "wb") as f:
    pickle.dump(le, f)

print("label_encoder.pkl saved successfully!")

label_encoder.pkl saved successfully!